apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryapp
spec:
  selector:
    matchLabels:
      app: libraryapp
  replicas:  {{ .Values.app.replicacount }}
  template:
    metadata:
      labels:
        app: libraryapp
    spec:
      containers:
        - name: libraryapp
          image: {{ .Values.app.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password